name: Java CI with Maven

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Make Maven Runs Well
      run: chmod +x mvnw
    - name: Clean Maven Cache
      run: mvn clean install
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
          name: netty
          path: kcp-netty/target/kcp-netty-1.5.1.jar
